apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksworkshop-eksctl
  region: eu-west-1

nodeGroups:
  - name: windows-ng
    amiFamily: WindowsServer2019CoreContainer
    desiredCapacity: 1
    instanceType: t2.large
    ssh:
      enableSsm: true